const KEYCODES = [
  { value: "A", label: "A a", keyCode: 65 },
  { value: "B", label: "B b", keyCode: 66 },
  { value: "C", label: "C c", keyCode: 67 },
  { value: "D", label: "D d", keyCode: 68 },
  { value: "E", label: "E e", keyCode: 69 },
  { value: "F", label: "F f", keyCode: 70 },
  { value: "G", label: "G g", keyCode: 71 },
  { value: "H", label: "H h", keyCode: 72 },
  { value: "I", label: "I i", keyCode: 73 },
  { value: "J", label: "J j", keyCode: 74 },
  { value: "K", label: "K k", keyCode: 75 },
  { value: "L", label: "L l", keyCode: 76 },
  { value: "M", label: "M m", keyCode: 77 },
  { value: "N", label: "N n", keyCode: 78 },
  { value: "O", label: "O o", keyCode: 79 },
  { value: "P", label: "P p", keyCode: 80 },
  { value: "Q", label: "Q q", keyCode: 81 },
  { value: "R", label: "R r", keyCode: 82 },
  { value: "S", label: "S s", keyCode: 83 },
  { value: "T", label: "T t", keyCode: 84 },
  { value: "U", label: "U u", keyCode: 85 },
  { value: "V", label: "V v", keyCode: 86 },
  { value: "W", label: "W w", keyCode: 87 },
  { value: "X", label: "X x", keyCode: 88 },
  { value: "Y", label: "Y y", keyCode: 89 },
  { value: "Z", label: "Z z", keyCode: 90 },
  { value: "D0", label: "0 )", keyCode: 48 },
  { value: "D1", label: "1 !", keyCode: 49 },
  { value: "D2", label: "2 @", keyCode: 50 },
  { value: "D3", label: "3 #", keyCode: 51 },
  { value: "D4", label: "4 $", keyCode: 52 },
  { value: "D5", label: "5 %", keyCode: 53 },
  { value: "D6", label: "6 ^", keyCode: 54 },
  { value: "D7", label: "7 &", keyCode: 55 },
  { value: "D8", label: "8 *", keyCode: 56 },
  { value: "D9", label: "9 (", keyCode: 57 },
  { value: "Escape", label: "Escape", keyCode: 27 },
  { value: "F1", label: "F1", keyCode: 112 },
  { value: "F2", label: "F2", keyCode: 113 },
  { value: "F3", label: "F3", keyCode: 114 },
  { value: "F4", label: "F4", keyCode: 115 },
  { value: "F5", label: "F5", keyCode: 116 },
  { value: "F6", label: "F6", keyCode: 117 },
  { value: "F7", label: "F7", keyCode: 118 },
  { value: "F8", label: "F8", keyCode: 119 },
  { value: "F9", label: "F9", keyCode: 120 },
  { value: "F10", label: "F10", keyCode: 121 },
  { value: "F11", label: "F11", keyCode: 122 },
  { value: "F12", label: "F12", keyCode: 123 },
  { value: "Grave", label: "Grave (` ~)", keyCode: 192 },
  { value: "Minus", label: "Minus (- _)", keyCode: 189 },
  { value: "Plus", label: "Plus (= +)", keyCode: 187 },
  { value: "Back", label: "Backspace", keyCode: 8 },
  { value: "Tab", label: "Tab", keyCode: 9 },
  { value: "OpenBrackets", label: "Open Brackets ([ {)", keyCode: 219 },
  { value: "CloseBrackets", label: "Close Brackets ()] })", keyCode: 221 },
  { value: "Backslash", label: "Backslash (\\ |)", keyCode: 220 },
  { value: "CapsLock", label: "CapsLock", keyCode: 20 },
  { value: "Semicolon", label: "Semicolon (; :)", keyCode: 186 },
  { value: "Quote", label: "Quote (' \")", keyCode: 222 },
  { value: "Enter", label: "Enter", keyCode: 13 },
  { value: "Comma", label: "Comma (, <)", keyCode: 188 },
  { value: "Period", label: "Period (. >)", keyCode: 190 },
  { value: "Slash", label: "Slash (/ ?)", keyCode: 191 },
  { value: "Shift", label: "Shift", keyCode: 16 },
  { value: "LShift", label: "Left Shift", keyCode: 160 },
  { value: "RShift", label: "Right Shift", keyCode: 161 },
  { value: "Control", label: "Control", keyCode: 17 },
  { value: "LControl", label: "Left Control", keyCode: 162 },
  { value: "RControl", label: "Right Control", keyCode: 163 },
  { value: "Alt", label: "Alt", keyCode: 18 },
  { value: "LAlt", label: "Left Alt", keyCode: 164 },
  { value: "RAlt", label: "Right Alt", keyCode: 165 },
  { value: "LWin", label: "Left Windows", keyCode: 91 },
  { value: "RWin", label: "Right Windows", keyCode: 92 },
  { value: "Mod", label: "Mod", keyCode: 15 },
  { value: "Space", label: "Space bar", keyCode: 32 },
  { value: "PrintScreen", label: "Print Screen (Screenshot)", keyCode: 44 },
  { value: "ScrollLock", label: "ScrollLock", keyCode: 145 },
  { value: "NumLock", label: "NumLock", keyCode: 144 },
  { value: "Numpad0", label: "Numpad 0", keyCode: 96 },
  { value: "Numpad1", label: "Numpad 1", keyCode: 97 },
  { value: "Numpad2", label: "Numpad 2", keyCode: 98 },
  { value: "Numpad3", label: "Numpad 3", keyCode: 99 },
  { value: "Numpad4", label: "Numpad 4", keyCode: 100 },
  { value: "Numpad5", label: "Numpad 5", keyCode: 101 },
  { value: "Numpad6", label: "Numpad 6", keyCode: 102 },
  { value: "Numpad7", label: "Numpad 7", keyCode: 103 },
  { value: "Numpad8", label: "Numpad 8", keyCode: 104 },
  { value: "Numpad9", label: "Numpad 9", keyCode: 105 },
  { value: "Multiply", label: "Numpad Multiply", keyCode: 106 },
  { value: "Add", label: "Numpad Add", keyCode: 107 },
  { value: "Separator", label: "Numpad Separator", keyCode: 108 },
  { value: "Subtract", label: "Numpad Subtract", keyCode: 109 },
  { value: "Decimal", label: "Numpad Decimal", keyCode: 110 },
  { value: "Divide", label: "Numpad Divide", keyCode: 111 },
  { value: "F13", label: "F13", keyCode: 124 },
  { value: "F14", label: "F14", keyCode: 125 },
  { value: "F15", label: "F15", keyCode: 126 },
  { value: "F16", label: "F16", keyCode: 127 },
  { value: "F17", label: "F17", keyCode: 128 },
  { value: "F18", label: "F18", keyCode: 129 },
  { value: "F19", label: "F19", keyCode: 130 },
  { value: "F20", label: "F20", keyCode: 131 },
  { value: "F21", label: "F21", keyCode: 132 },
  { value: "F22", label: "F22", keyCode: 133 },
  { value: "F23", label: "F23", keyCode: 134 },
  { value: "F24", label: "F24", keyCode: 135 },
  { value: "Apps", label: "Apps", keyCode: 93 },
  { value: "Sleep", label: "Sleep", keyCode: 95 },
  { value: "Pause", label: "Pause", keyCode: 19 },
  { value: "Clear", label: "Clear", keyCode: 12 },
  { value: "PageUp", label: "Page Up", keyCode: 33 },
  { value: "PageDown", label: "Page Down", keyCode: 34 },
  { value: "End", label: "End", keyCode: 35 },
  { value: "Home", label: "Home", keyCode: 36 },
  { value: "Left", label: "Left Arrow", keyCode: 37 },
  { value: "Up", label: "Up Arrow", keyCode: 38 },
  { value: "Right", label: "Right Arrow", keyCode: 39 },
  { value: "Down", label: "Down Arrow", keyCode: 40 },
  { value: "Select", label: "Select", keyCode: 41 },
  { value: "Print", label: "Print", keyCode: 42 },
  { value: "Execute", label: "Execute", keyCode: 43 },
  { value: "Insert", label: "Insert", keyCode: 45 },
  { value: "Delete", label: "Delete", keyCode: 46 },
  { value: "Help", label: "Help", keyCode: 47 },
  { value: "BrowserBack", label: "Browser Back", keyCode: 166 },
  { value: "BrowserForward", label: "Browser Forward", keyCode: 167 },
  { value: "BrowserRefresh", label: "Browser Refresh", keyCode: 168 },
  { value: "BrowserStop", label: "Browser Stop", keyCode: 169 },
  { value: "BrowserSearch", label: "Browser Search", keyCode: 170 },
  { value: "BrowserFavorites", label: "Browser Favorites", keyCode: 171 },
  { value: "BrowserHome", label: "Browser Home", keyCode: 172 },
  { value: "VolumeMute", label: "Volume Mute", keyCode: 173 },
  { value: "VolumeDown", label: "Volume Down", keyCode: 174 },
  { value: "VolumeUp", label: "Volume Up", keyCode: 175 },
  { value: "MediaNextTrack", label: "Media Next Track", keyCode: 176 },
  { value: "MediaPrevTrack", label: "Media Prev Track", keyCode: 177 },
  { value: "MediaStop", label: "Media Stop", keyCode: 178 },
  { value: "MediaPlayPause", label: "Media Play Pause", keyCode: 179 },
  { value: "LaunchMail", label: "Launch Mail", keyCode: 180 },
  { value: "LaunchMediaSelect", label: "Launch Media Select", keyCode: 181 },
  { value: "LaunchApp1", label: "Launch App1", keyCode: 182 },
  { value: "LaunchApp2", label: "Launch App2", keyCode: 183 },
  { value: "OEM8", label: "OEM8", keyCode: 223 },
  { value: "OEMAX", label: "OEMAX", keyCode: 225 },
  { value: "OEM102", label: "OEM102", keyCode: 226 },
  { value: "ICOHelp", label: "ICOHelp", keyCode: 227 },
  { value: "ProcessKey", label: "ProcessKey", keyCode: 229 },
  { value: "ICOClear", label: "ICOClear", keyCode: 230 },
  { value: "OEMReset", label: "OEMReset", keyCode: 233 },
  { value: "OEMJump", label: "OEMJump", keyCode: 234 },
  { value: "OEMPA1", label: "OEMPA1", keyCode: 235 },
  { value: "OEMPA2", label: "OEMPA2", keyCode: 236 },
  { value: "OEMPA3", label: "OEMPA3", keyCode: 237 },
  { value: "OEMWSCtrl", label: "OEMWSCtrl", keyCode: 238 },
  { value: "OEMCUSel", label: "OEMCUSel", keyCode: 239 },
  { value: "OEMAttn", label: "OEMAttn", keyCode: 240 },
  { value: "OEMFinish", label: "OEMFinish", keyCode: 241 },
  { value: "OEMCopy", label: "OEMCopy", keyCode: 242 },
  { value: "OEMAuto", label: "OEMAuto", keyCode: 243 },
  { value: "OEMEnlW", label: "OEMEnlW", keyCode: 244 },
  { value: "OEMBackTab", label: "OEMBackTab", keyCode: 245 },
  { value: "Attn", label: "Attn", keyCode: 246 },
  { value: "CrSel", label: "CrSel", keyCode: 247 },
  { value: "ExSel", label: "ExSel", keyCode: 248 },
  { value: "ErEoF", label: "ErEoF", keyCode: 249 },
  { value: "Play", label: "Play", keyCode: 250 },
  { value: "Zoom", label: "Zoom", keyCode: 251 },
  { value: "NoName", label: "NoName", keyCode: 252 },
  { value: "PA1", label: "PA1", keyCode: 253 },
  { value: "OEMClear", label: "OEMClear", keyCode: 254 },
  { value: "None", label: "None", keyCode: 0, hidden: true },
  { value: "LButton", label: "LButton", keyCode: 1, hidden: true },
  { value: "RButton", label: "RButton", keyCode: 2, hidden: true },
  { value: "Cancel", label: "Cancel", keyCode: 3, hidden: true },
  { value: "MButton", label: "MButton", keyCode: 4, hidden: true },
  { value: "XButton1", label: "XButton1", keyCode: 5, hidden: true },
  { value: "XButton2", label: "XButton2", keyCode: 6, hidden: true },
  { value: "7", label: "7", keyCode: 7, hidden: true },
  { value: "10", label: "10", keyCode: 10, hidden: true },
  { value: "11", label: "11", keyCode: 11, hidden: true },
  { value: "14", label: "14", keyCode: 14, hidden: true },
  { value: "Kana", label: "Kana", keyCode: 21, hidden: true },
  { value: "IMEOn", label: "IMEOn", keyCode: 22, hidden: true },
  { value: "Junja", label: "Junja", keyCode: 23, hidden: true },
  { value: "IMEFinal", label: "IMEFinal", keyCode: 24, hidden: true },
  { value: "Kanji", label: "Kanji", keyCode: 25, hidden: true },
  { value: "IMEOff", label: "IMEOff", keyCode: 26, hidden: true },
  { value: "IMEConvert", label: "IMEConvert", keyCode: 28, hidden: true },
  { value: "IMENonConvert", label: "IMENonConvert", keyCode: 29, hidden: true },
  { value: "IMEAccept", label: "IMEAccept", keyCode: 30, hidden: true },
  { value: "IMEModeChange", label: "IMEModeChange", keyCode: 31, hidden: true },
  { value: "58", label: "58", keyCode: 58, hidden: true },
  { value: "59", label: "59", keyCode: 59, hidden: true },
  { value: "60", label: "60", keyCode: 60, hidden: true },
  { value: "61", label: "61", keyCode: 61, hidden: true },
  { value: "62", label: "62", keyCode: 62, hidden: true },
  { value: "63", label: "63", keyCode: 63, hidden: true },
  { value: "64", label: "64", keyCode: 64, hidden: true },
  { value: "94", label: "94", keyCode: 94, hidden: true },
  { value: "136", label: "136", keyCode: 136, hidden: true },
  { value: "137", label: "137", keyCode: 137, hidden: true },
  { value: "138", label: "138", keyCode: 138, hidden: true },
  { value: "139", label: "139", keyCode: 139, hidden: true },
  { value: "140", label: "140", keyCode: 140, hidden: true },
  { value: "141", label: "141", keyCode: 141, hidden: true },
  { value: "142", label: "142", keyCode: 142, hidden: true },
  { value: "143", label: "143", keyCode: 143, hidden: true },
  { value: "FujitsuJisho", label: "FujitsuJisho", keyCode: 146, hidden: true },
  { value: "FujitsuMasshou", label: "FujitsuMasshou", keyCode: 147, hidden: true },
  { value: "FujitsuTouroku", label: "FujitsuTouroku", keyCode: 148, hidden: true },
  { value: "FujitsuLoya", label: "FujitsuLoya", keyCode: 149, hidden: true },
  { value: "FujitsuRoya", label: "FujitsuRoya", keyCode: 150, hidden: true },
  { value: "151", label: "151", keyCode: 151, hidden: true },
  { value: "152", label: "152", keyCode: 152, hidden: true },
  { value: "153", label: "153", keyCode: 153, hidden: true },
  { value: "154", label: "154", keyCode: 154, hidden: true },
  { value: "155", label: "155", keyCode: 155, hidden: true },
  { value: "156", label: "156", keyCode: 156, hidden: true },
  { value: "157", label: "157", keyCode: 157, hidden: true },
  { value: "158", label: "158", keyCode: 158, hidden: true },
  { value: "159", label: "159", keyCode: 159, hidden: true },
  { value: "184", label: "184", keyCode: 184, hidden: true },
  { value: "185", label: "185", keyCode: 185, hidden: true },
  { value: "193", label: "193", keyCode: 193, hidden: true },
  { value: "194", label: "194", keyCode: 194, hidden: true },
  { value: "195", label: "195", keyCode: 195, hidden: true },
  { value: "196", label: "196", keyCode: 196, hidden: true },
  { value: "197", label: "197", keyCode: 197, hidden: true },
  { value: "198", label: "198", keyCode: 198, hidden: true },
  { value: "199", label: "199", keyCode: 199, hidden: true },
  { value: "200", label: "200", keyCode: 200, hidden: true },
  { value: "201", label: "201", keyCode: 201, hidden: true },
  { value: "202", label: "202", keyCode: 202, hidden: true },
  { value: "203", label: "203", keyCode: 203, hidden: true },
  { value: "204", label: "204", keyCode: 204, hidden: true },
  { value: "205", label: "205", keyCode: 205, hidden: true },
  { value: "206", label: "206", keyCode: 206, hidden: true },
  { value: "207", label: "207", keyCode: 207, hidden: true },
  { value: "208", label: "208", keyCode: 208, hidden: true },
  { value: "209", label: "209", keyCode: 209, hidden: true },
  { value: "210", label: "210", keyCode: 210, hidden: true },
  { value: "211", label: "211", keyCode: 211, hidden: true },
  { value: "212", label: "212", keyCode: 212, hidden: true },
  { value: "213", label: "213", keyCode: 213, hidden: true },
  { value: "214", label: "214", keyCode: 214, hidden: true },
  { value: "215", label: "215", keyCode: 215, hidden: true },
  { value: "216", label: "216", keyCode: 216, hidden: true },
  { value: "217", label: "217", keyCode: 217, hidden: true },
  { value: "218", label: "218", keyCode: 218, hidden: true },
  { value: "224", label: "224", keyCode: 224, hidden: true },
  { value: "ICO00", label: "ICO00", keyCode: 228, hidden: true },
  { value: "Packet", label: "Packet", keyCode: 231, hidden: true },
  { value: "232", label: "232", keyCode: 232, hidden: true },
];
export default KEYCODES
